name: " Thank you action"
description: "Answer pull requests"
author: "Igor"

inputs:
  GITHUB_TOKEN:
    description: "Github Token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
